apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app-1
  template:
    metadata:
      labels:
        app: simple-app-1
    spec:
      containers:
      - name: simple-app
        image: styagi935/simple-app-6.0.0:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
